name: CI
on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      attest-package:
        description: "Create GitHub provenance attestation for the package."
        default: "false"
        type: string
    outputs:
      artifact-name:
        description: "Name of the uploaded artifact; use for artifact retrieval."
        value: ${{ jobs.package.outputs.artifact-name }}

# Cancel active CI runs for a PR before starting another run
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

defaults:
  run:
    shell: bash

env:
  FORCE_COLOR: "1"

jobs:
  pre-commit:
    name: Pre-commit checks
    uses: beeware/.github/.github/workflows/pre-commit-run.yml@main
    with:
      pre-commit-source: "--group pre-commit"

  towncrier:
    name: Check towncrier
    permissions:
      contents: read
      pull-requests: write
    uses: beeware/.github/.github/workflows/towncrier-run.yml@main
    with:
      tox-source: "--group tox-uv"

  package:
    name: Build installer
    needs: [pre-commit, towncrier]
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macOS
            platform: macOS-latest

          - name: windows
            platform: windows-latest

          - name: ubuntu-24.04
            platform: ubuntu-24.04
            system-dependencies: |
              sudo apt-get update
              sudo apt install gir1.2-gtk-3.0 gir1.2-webkit2-4.1 \
                libcairo2-dev libcanberra-gtk3-module libgirepository-2.0-0 \
                libgirepository-2.0-dev

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0

      - name: Install system dependencies
        if: matrix.system-dependencies
        run: ${{ matrix.system-dependencies }}

      - name: Build package
        run: |
          uvx briefcase package --adhoc-sign

      - name: Upload artefacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: installer-${{ matrix.name }}
          path: dist
